# Generated by Django 5.1.2 on 2024-10-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_profile_otp_attempts_profile_otp_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='otp_attempts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='otp_created_at',
        ),
    ]
